CREATE DATABASE IF NOT EXISTS CVEData;
USE CVEData;

CREATE TABLE IF NOT EXISTS CVEs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cve_id VARCHAR(255) NOT NULL UNIQUE,
    cvss_score FLOAT DEFAULT 0,
    last_modified DATE,
    data JSON
);
